### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by simonjenny** [oneduo/nova-file-manager#178]
The Package can not be installed with Laravel 10.x and Nova 4.0:

Your requirements could not be resolved to an installable set of packages.
 Problem 1
    - Root composer.json requires pion/laravel-chunk-upload ^1.5.1 -> satisfiable by pion/laravel-chunk-upload[v1.5.1].
    - pion/laravel-chunk-upload v1.5.1 requires illuminate/http 5.2 - 5.8 | ^6.0 | ^7.0 | ^8.0 | ^9.0 -> found illuminate/http[v5.2.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but it conflicts with your root composer.json require (^10.1).
Installation failed, reverting ./composer.json and ./composer.lock to their original content.

Most likely because of the pion/laravel-chunk-uploads requirement of illuminate/http Version up until 9.0 but there is 10.1 installed.

**Comment by Rezrazi** [comment]
Hi @simonjenny 

Thank you for your report, and yes we're aware that the package is currently not compatible with Laravel 10, and yes it is due to a main third party dependency of the package which is pionl/laravel-chunk-uploads

We are following the developments here https://github.com/pionl/laravel-chunk-upload/pull/151 and hoping for it to upgraded in the next few days.

Additionally, we're looking behind the scene at dropping this dependency perhaps and embedding chunk uploads and resumability within our package

Thanks !

**Comment by pionl** [comment]
Hi, did not know it is used here. [New version released](https://github.com/pionl/laravel-chunk-upload/issues/147#issuecomment-1470843938).

**Comment by mikaelpopowicz** [comment]
Hi @pionl 

Thank you for the release.

Feel free to try the package.
